// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "v1.h"

std::string v1::echo(const std::string& text)
{
    return "Hi, " + text;
}

